version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_CONFIG=${NOTION_CONFIG}
      - SENTRY_NOTION_INTEGRATION_CLIENT_SECRET=${SENTRY_NOTION_INTEGRATION_CLIENT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
